const data = {
    products: [
      {
        _id: 1,
        name: 'Nike Slim Shirt',
        category: 'Sport',
        image: '/image/img.jpeg'   
        ,price: 120,
        brand: 'Nike',
        rating: 5,
        numReviews: 50,
        discription: "High quality product",
        CountInStock: "10",
      },
      {
        _id: 2,
        name: 'Adidas Shoes',
        category: 'Sport',
        image: '/image/adidas.avif',
        price: 250,
        brand: 'Adidas',
        rating: 4,
        numReviews: 20,
        discription: "High quality product",
        CountInStock: "5",
      },
      {
        _id: 3,
        name: 'Apple Watch Series 8',
        category: 'Electronics',
        image: '/image/apple.jpg',
        price: 399,
        brand: 'Apple',
        rating: 4.5,
        numReviews: 120,
        discription: "High quality product",
        CountInStock: "13",
      },
      {
        _id: 4,
        name: 'Sony Noise-Cancelling Headphones',
        category: 'Electronics',
        image: '/image/headphones.jpg',
        price: 199,
        brand: 'Sony',
        rating: 2.5,
        numReviews: 85,
        discription: "High quality product",
        CountInStock: "7",
      },
      {
        _id: 5,
        name: 'Levi’s Jeans',
        category: 'Fashion',
        image: '/image/levis.jpg',
        price: 80,
        brand: 'Levi’s',
        rating: 3.5,
        numReviews: 45,
        discription: "High quality product",
        CountInStock: "0",
      },
      {
        _id: 6,
        name: 'Pull & Bear',
        category: 'Fashion',
        image: '/image/pull&bear.jpeg',
        price: 180,
        brand: 'P&B',
        rating: 3,
        numReviews: 45,
        discription: "High quality product",
        CountInStock: "8",
      },
    ],
  };
  export default data;